
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\vo000010\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://defra-sdds-dev2.api.crm11.dynamics.com" /namespace:"SDDS.Plugin.EBG" /SuppressGeneratedCodeAttribute /out:"C:\Users\vo000010\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" 
//------------------------------------------------------------------------------

namespace SDDS.Plugin.EBG
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msft_DataState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Default", 0)]
		Default = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Retain", 1)]
		Retain = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_AdvisorType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Advisor ", 0)]
		Advisor = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lead advisor", 1)]
		Leadadvisor = 100000001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_application_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Allocated for assessment", 2, "#499B51")]
		Allocatedforassessment = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Awaiting Allocation", 1, "#F10909")]
		AwaitingAllocation = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Closed", 9)]
		Closed = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Granted", 4, "#B197CE")]
		Granted = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 7, "#0000ff")]
		Inactive = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Modification in Progress", 10, "#961b1b")]
		ModificationinProgress = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not Granted", 6, "#6b6fcf")]
		NotGranted = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Paused", 5, "#D62FD1")]
		Paused = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Received", 0, "#12988A")]
		Received = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Under Assessment", 3, "#48F90B")]
		UnderAssessment = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Withdrawn", 8, "#de0b0b")]
		Withdrawn = 100000006,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_applicationcategory
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agriculture/Farming/Fishing/Forestry/Nature Conservation", 0)]
		AgricultureFarmingFishingForestryNatureConservation = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Archeological investigation", 1)]
		Archeologicalinvestigation = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Barn Conversion", 2)]
		BarnConversion = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Commercial", 3)]
		Commercial = 100000019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Communications", 4)]
		Communications = 100000017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Energy generation and Energy Supply", 5)]
		EnergygenerationandEnergySupply = 100000016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Flood and Coastal defences", 6)]
		FloodandCoastaldefences = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Health and safety", 7)]
		Healthandsafety = 100000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Heritage/Historical conservation", 8)]
		HeritageHistoricalconservation = 100000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Householder home improvements", 9)]
		Householderhomeimprovements = 100000013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Industrial or Manufacturing", 11)]
		IndustrialorManufacturing = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Listed buildings", 12)]
		Listedbuildings = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nationally Significant Infrastructure Projects", 14)]
		NationallySignificantInfrastructureProjects = 100000018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 23)]
		Other = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Public buildings and public land", 15)]
		Publicbuildingsandpublicland = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quarrying and mining", 13)]
		Quarryingandmining = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Registered Places of worship", 16)]
		RegisteredPlacesofworship = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Residential housing (not householder improvements)", 10)]
		Residentialhousing_nothouseholderimprovements = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Scheduled monuments", 17)]
		Scheduledmonuments = 452120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tourism and leisure", 18)]
		Tourismandleisure = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Traditional farm buildings in a countryside stewardship agreement", 20)]
		Traditionalfarmbuildingsinacountrysidestewardshipagreement = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transport, including roads", 19)]
		Transportincludingroads = 100000012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Waste management", 21)]
		Wastemanagement = 100000014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Water bodies, water supply and treatment", 22)]
		Waterbodieswatersupplyandtreatment = 100000015,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_ApplicationSubject
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Badger", 1)]
		Badger = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bats", 0)]
		Bats = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Great crested newts", 2)]
		Greatcrestednewts = 100000002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_ApplicationType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Modification", 1, "#ad6363")]
		Modification = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("New", 0, "#41cc66")]
		New = 452120000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_applicatioonAssessmentCategory
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Full Manual", 2)]
		FullManual = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Normal", 0)]
		Normal = 452120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Targeted", 1)]
		Targeted = 452120001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Assessingteam
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Central Team", 1)]
		CentralTeam = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Delivery Team", 0)]
		DeliveryTeam = 100000000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_assessment
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Charge Request", 8)]
		ChargeRequest = 100000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Decision", 9)]
		Decision = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Designated site", 12)]
		Designatedsite = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Disease Risk", 1)]
		DiseaseRisk = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Experience", 5)]
		Experience = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FCS", 2)]
		FCS = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("HRA", 6)]
		HRA = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("HRA Assessment", 11)]
		HRAAssessment = 100000013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IROPI", 0)]
		IROPI = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Maps", 13)]
		Maps = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("NSA", 3)]
		NSA = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Survey", 7)]
		Survey = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Task", 10)]
		Task = 100000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Technical", 4)]
		Technical = 100000004,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_AssessmentOutcome
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Grant", 0)]
		Grant = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not Grant", 1)]
		NotGrant = 100000001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Assessmenttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Desk Assessment", 2)]
		DeskAssessment = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Desk based - email", 3)]
		Deskbasedemail = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Desk based - interim report check", 4)]
		Deskbasedinterimreportcheck = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Site Visit", 0)]
		SiteVisit = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Telephone Assessment", 1)]
		TelephoneAssessment = 100000001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_baterwhyisalicenceneeded
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Capture / Take", 0)]
		CaptureTake = 452120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Damage Breeding Site", 3)]
		DamageBreedingSite = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Damage Resting Place", 5)]
		DamageRestingPlace = 452120005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Destroy Breeding Site", 4)]
		DestroyBreedingSite = 452120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Destroy Resting Place", 6)]
		DestroyRestingPlace = 452120006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Disturb", 1)]
		Disturb = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transport", 2)]
		Transport = 452120002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Chargetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Exempted", 0)]
		Exempted = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fixed", 2)]
		Fixed = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hourly", 1)]
		Hourly = 100000001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_commpreference
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email", 0)]
		Email = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Post", 1)]
		Post = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Telephone", 2)]
		Telephone = 100000002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Compensationmeasureslocation
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("A bespoke new building", 2)]
		Abespokenewbuilding = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Another existing building", 1)]
		Anotherexistingbuilding = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 3)]
		Other = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("The same building", 0)]
		Thesamebuilding = 452120000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_compensationmesaurestypes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bat box", 3)]
		Batbox = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bat tile/brick/tube", 4)]
		Battilebricktube = 452120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Creation of new access point/s", 6)]
		Creationofnewaccesspoints = 452120006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Creation of new crevice/s", 5)]
		Creationofnewcrevices = 452120005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Greenbridge", 10)]
		Greenbridge = 452120010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Habitat Reinstatement (for temporary impacts)", 7)]
		HabitatReinstatement_fortemporaryimpacts = 452120007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Heated bat box", 2)]
		Heatedbatbox = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Like-for-like roost creation", 1)]
		Likeforlikeroostcreation = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("N/A - None", 0)]
		NANone = 452120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 12)]
		Other = 452120012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Provision of new foraging or commuting habitat", 8)]
		Provisionofnewforagingorcommutinghabitat = 452120008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tree veteranisation", 9)]
		Treeveteranisation = 452120009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Underpass", 11)]
		Underpass = 452120011,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Consentgranted
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Conservation Area Consent", 7)]
		ConservationAreaConsent = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Demolition consent (under Building Act 1984)", 1)]
		Demolitionconsent_underBuildingAct1984 = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Full Planning Permission", 0)]
		FullPlanningPermission = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Highways Act Consent", 3)]
		HighwaysActConsent = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Listed Building Consent", 2)]
		ListedBuildingConsent = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mineral Consent", 4)]
		MineralConsent = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mineral Consent (Review of Mineral Planning Permission submitted to Mi", 5)]
		MineralConsent_ReviewofMineralPlanningPermissionsubmittedtoMi = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mineral Consent with Review of Mineral Planning Permission", 10)]
		MineralConsentwithReviewofMineralPlanningPermission = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other consent type", 11)]
		Otherconsenttype = 100000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outline Planning Permission", 6)]
		OutlinePlanningPermission = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tree Preservation Order", 8)]
		TreePreservationOrder = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Utilities Consent", 9)]
		UtilitiesConsent = 100000009,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_consentrequired
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Demolition consent (under Building Act 1984)", 1)]
		Demolitionconsent_underBuildingAct1984 = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("No consent required", 4)]
		Noconsentrequired = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other type of consent required", 2)]
		Othertypeofconsentrequired = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Permitted Development (under Town and Country Planning Act 1990)", 3)]
		PermittedDevelopment_underTownandCountryPlanningAct1990 = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Planning-related", 0)]
		Planningrelated = 100000000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_ConsentStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Consent Granted", 0)]
		ConsentGranted = 452120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Consent not required (e.g. Permitted Development)", 3)]
		Consentnotrequired_egPermittedDevelopment = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Decision Outstanding", 2)]
		DecisionOutstanding = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 4)]
		Other = 452120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outline Consent Granted", 1)]
		OutlineConsentGranted = 452120001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_designatedsitename_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_designatedsites_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_DiseaseriskOutcome
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("High risk", 3)]
		Highrisk = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Low risk", 1)]
		Lowrisk = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Medium risk", 2)]
		Mediumrisk = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("No Risk", 0)]
		NoRisk = 100000003,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Exemptionreason
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Conservation of protected species, including protection of bat roosts", 4)]
		Conservationofprotectedspeciesincludingprotectionofbatroosts = 452120005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Conserve scheduled monuments, listed buildings, places of worship, or traditional" +
			" farm buildings", 5)]
		Conservescheduledmonumentslistedbuildingsplacesofworshiportraditionalfarmbuildings = 452120006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Home improvement through householder planning permission or permitted development" +
			"", 1)]
		Homeimprovementthroughhouseholderplanningpermissionorpermitteddevelopment = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 6)]
		Other = 452120007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Preserving public health and safety", 0)]
		Preservingpublichealthandsafety = 452120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Preventing damage to livestock, crops, timber or property", 2)]
		Preventingdamagetolivestockcropstimberorproperty = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Scientific, research or educational purposes", 3)]
		Scientificresearchoreducationalpurposes = 452120004,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_ImpactforRoost
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Disturbance Only", 4)]
		DisturbanceOnly = 452120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 5)]
		Other = 452120005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Permanent Damage", 3)]
		PermanentDamage = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Permanent Destruction", 2)]
		PermanentDestruction = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Temporary Damage", 1)]
		TemporaryDamage = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Temporary Loss", 0)]
		TemporaryLoss = 452120000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_leveltype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("High Risk", 1)]
		HighRisk = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Low Risk", 0)]
		LowRisk = 452120000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_LicencePaymentStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Paid", 1)]
		Paid = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pending", 0)]
		Pending = 452120000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_licensableaction_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_license_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0, "#0000ff")]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Draft", 1, "#0000ff")]
		Draft = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Expired (ROA Due)", 3, "#d44e4e")]
		Expired_ROADue = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Expired (ROA Received)", 5, "#a362a3")]
		Expired_ROAReceived = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Expired (ROA Received late)", 6, "#d6ba56")]
		Expired_ROAReceivedlate = 452120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Granted (ROA Received)", 4, "#14c443")]
		Granted_ROAReceived = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 2, "#0000ff")]
		Inactive = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Revoked", 7, "#7a5656")]
		Revoked = 452120005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Revoked (ROA Received)", 8)]
		Revoked_ROAReceived = 452120006,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_licenseActivity_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_licensemethod_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Draft", 2)]
		Draft = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_LicenseMethod1
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Any form of artificial light or any mirror or dazzling device", 33)]
		Anyformofartificiallightoranymirrorordazzlingdevice = 100000033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Any mist or net trap", 51)]
		Anymistornettrap = 100000051,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Any smoke or gas calculated to cause bodily injury", 34)]
		Anysmokeorgascalculatedtocausebodilyinjury = 100000034,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Artificial lighting or any mirror or dazzling device", 54)]
		Artificiallightingoranymirrorordazzlingdevice = 100000054,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Automatic or semi automatic weapon", 30)]
		Automaticorsemiautomaticweapon = 100000030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("badtest", 91)]
		badtest = 100000091,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bottle Trapping", 80)]
		BottleTrapping = 100000080,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("By hand", 0)]
		Byhand = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("By Hand Test", 88)]
		ByHandTest = 100000088,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("By static hand-held net", 1)]
		Bystatichandheldnet = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Close human presence", 48)]
		Closehumanpresence = 100000048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Damaging a sett by hand and mechanical means", 12)]
		Damagingasettbyhandandmechanicalmeans_100000012 = 100000012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Damaging a sett by hand and mechanical means", 69)]
		Damagingasettbyhandandmechanicalmeans_100000069 = 100000069,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Damaging a sett by  hand and mechanical  means", 78)]
		Damagingasettbyhandandmechanicalmeans_100000078 = 100000078,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Destruction of holt by hand or mechanical means", 24)]
		Destructionofholtbyhandormechanicalmeans = 100000024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Destruction of sett", 3)]
		Destructionofsett_100000003 = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Destruction of sett", 75)]
		Destructionofsett_100000075 = 100000075,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Destruction of the vacant sett by hand and mechanical means", 13)]
		Destructionofthevacantsettbyhandandmechanicalmeans_100000013 = 100000013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Destruction of the vacant sett by hand and mechanical means", 74)]
		Destructionofthevacantsettbyhandandmechanicalmeans_100000074 = 100000074,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Destruction of the vacant sett by hand and  mechanical means", 85)]
		Destructionofthevacantsettbyhandandmechanicalmeans_100000085 = 100000085,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Destructive search by soft demolition", 4)]
		Destructivesearchbysoftdemolition = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Destructive search of burrows", 38)]
		Destructivesearchofburrows = 100000038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Device for illuminating a target", 53)]
		Deviceforilluminatingatarget = 100000053,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Discharge a missile to administer the stupefying drug or muscle relaxing agent", 20)]
		Dischargeamissiletoadministerthestupefyingdrugormusclerelaxingagent = 100000020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Disturbance by human or artificial means", 23)]
		Disturbancebyhumanorartificialmeans = 100000023,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Disturbance by noise or vibration", 7)]
		Disturbancebynoiseorvibration = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Disturbance of badgers", 14)]
		Disturbanceofbadgers = 100000014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Disturbance of badgers As Appropriate Method not known", 16)]
		DisturbanceofbadgersAsAppropriateMethodnotknown = 100000016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("disturbance of badgers by hand", 90)]
		disturbanceofbadgersbyhand = 100000090,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Electrical device for killing or stunning", 28)]
		Electricaldeviceforkillingorstunning = 100000028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Enclosure", 82)]
		Enclosure = 100000082,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Endoscopes", 9)]
		Endoscopes = 100000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Exclusion by permanent amphibian fencing", 84)]
		Exclusionbypermanentamphibianfencing = 100000084,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Exclusion device as specified", 22)]
		Exclusiondeviceasspecified = 100000022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Falconry", 57)]
		Falconry = 100000057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fencing", 87)]
		Fencing = 100000087,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hand held tools", 99)]
		Handheldtools = 100000099,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hand Search", 95)]
		HandSearch = 100000095,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hand tools", 81)]
		Handtools = 100000081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("illumination (intentional by torch)", 6)]
		illumination_intentionalbytorch = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Immobilise with a stupefying drugs or muscle-relaxing agent", 67)]
		Immobilisewithastupefyingdrugsormusclerelaxingagent = 100000067,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Keeping in a prescribed manner", 17)]
		Keepinginaprescribedmanner = 100000017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Killing badgers by mechanical means", 68)]
		Killingbadgersbymechanicalmeans = 100000068,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Live capture trap", 39)]
		Livecapturetrap = 100000039,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Machinery", 50)]
		Machinery = 100000050,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mechanical demolition Disturbance by", 5)]
		MechanicaldemolitionDisturbanceby = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mechanical excavation", 79)]
		Mechanicalexcavation = 100000079,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mechanical Excavation", 89)]
		MechanicalExcavation = 100000089,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Method not known", 44)]
		Methodnotknown_100000044 = 100000044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Method not known", 45)]
		Methodnotknown_100000045 = 100000045,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Method not known", 72)]
		Methodnotknown_100000072 = 100000072,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nest box/Nest Tube", 94)]
		NestboxNestTube = 100000094,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nest destruction", 46)]
		Nestdestruction = 100000046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nest relocation", 47)]
		Nestrelocation = 100000047,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Net", 42)]
		Net = 100000042,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Obstructing access by blocking or proofing", 11)]
		Obstructingaccessbyblockingorproofing_100000011 = 100000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Obstructing access by blocking or proofing", 77)]
		Obstructingaccessbyblockingorproofing_100000077 = 100000077,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Obstructing access to sett entrances by blocking or proofing", 40)]
		Obstructingaccesstosettentrancesbyblockingorproofing_100000040 = 100000040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Obstructing access to sett entrances by blocking or proofing", 70)]
		Obstructingaccesstosettentrancesbyblockingorproofing_100000070 = 100000070,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Obstructing access to sett entrances by means of a fence incorporating one-way ba" +
			"dger gates", 15)]
		Obstructingaccesstosettentrancesbymeansofafenceincorporatingonewaybadgergates_100000015 = 100000015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Obstructing access to sett entrances by means of a fence incorporating one-way ba" +
			"dger gates", 19)]
		Obstructingaccesstosettentrancesbymeansofafenceincorporatingonewaybadgergates_100000019 = 100000019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Obstructing access to sett entrances by means of a fence incorporating one-way ba" +
			"dger gates", 41)]
		Obstructingaccesstosettentrancesbymeansofafenceincorporatingonewaybadgergates_100000041 = 100000041,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Obstructing access to sett entrances by means of a fence incorporating one-way ba" +
			"dger gates", 73)]
		Obstructingaccesstosettentrancesbymeansofafenceincorporatingonewaybadgergates_100000073 = 100000073,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("obstructing badgers by way blocking", 98)]
		obstructingbadgersbywayblocking = 100000098,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Obstructing sett entrances by means of one-way badger gate", 71)]
		Obstructingsettentrancesbymeansofonewaybadgergate = 100000071,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Obstructing sett entrances by means of one-way badger gates", 10)]
		Obstructingsettentrancesbymeansofonewaybadgergates = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Obstructing sett entrances by means of one-way Badger gates", 76)]
		ObstructingsettentrancesbymeansofonewayBadgergates = 100000076,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 93)]
		Other = 100000093,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other method not specified", 43)]
		Othermethodnotspecified = 100000043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pitfall trapping and refugia", 83)]
		Pitfalltrappingandrefugia = 100000083,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Plant", 66)]
		Plant = 100000066,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Poisonous, poisoned or stupefying substance", 29)]
		Poisonouspoisonedorstupefyingsubstance = 100000029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Public exhibition or competition of captive bred live wild bird(s)", 61)]
		Publicexhibitionorcompetitionofcaptivebredlivewildbird_s = 100000061,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("rad licence method", 96)]
		radlicencemethod = 100000096,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Release", 65)]
		Release = 100000065,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Removal of vegetation to bare earth", 36)]
		Removalofvegetationtobareearth = 100000036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Removal of vegetation to bare earth and water draw down", 37)]
		Removalofvegetationtobareearthandwaterdrawdown = 100000037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Round up and cull", 52)]
		Roundupandcull = 100000052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Selling", 59)]
		Selling = 100000059,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Shooting", 18)]
		Shooting = 100000018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Shooting and falconry", 56)]
		Shootingandfalconry = 100000056,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Shooting to kill to reduce population", 64)]
		Shootingtokilltoreducepopulation = 100000064,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Shooting to kill to reinforce scaring", 63)]
		Shootingtokilltoreinforcescaring = 100000063,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sighting device for night shooting", 32)]
		Sightingdevicefornightshooting = 100000032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Single stage habitat removal - active season", 97)]
		Singlestagehabitatremovalactiveseason = 100000097,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Single stage habitat removal - hibernation season", 92)]
		Singlestagehabitatremovalhibernationseason = 100000092,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Snare", 25)]
		Snare = 100000025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Spring operated traps", 49)]
		Springoperatedtraps = 100000049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Take by hand only", 60)]
		Takebyhandonly = 100000060,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Temporary exclusion", 2)]
		Temporaryexclusion = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Temporary obstruction of roost access", 8)]
		Temporaryobstructionofroostaccess = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("To sell captive bred birds", 62)]
		Tosellcaptivebredbirds = 100000062,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Trap or snare", 27)]
		Traporsnare = 100000027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Trapping", 58)]
		Trapping = 100000058,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Trapping (relocation)", 21)]
		Trapping_relocation = 100000021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Two stage habitat removal", 86)]
		Twostagehabitatremoval = 100000086,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Use a decoy", 26)]
		Useadecoy = 100000026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Use of sound recording as a decoy", 55)]
		Useofsoundrecordingasadecoy = 100000055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Uses a device for illuminating a target", 31)]
		Usesadeviceforilluminatingatarget = 100000031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Uses a mechanically propelled vehicle", 35)]
		Usesamechanicallypropelledvehicle = 100000035,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Locationofroost
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Above door or window lintel", 15)]
		Abovedoororwindowlintel = 452120015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Associated with a soffit box", 6)]
		Associatedwithasoffitbox = 452120006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Associated with fascias", 7)]
		Associatedwithfascias = 452120007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Associated with window area (sill/panes/surround)", 13)]
		Associatedwithwindowarea_sillpanessurround = 452120013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Gap associated with chimney", 17)]
		Gapassociatedwithchimney = 452120017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Gap at top of gable wall", 16)]
		Gapattopofgablewall = 452120016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Gap under felt", 9)]
		Gapunderfelt = 452120009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Gap within brickwork or stonework", 12)]
		Gapwithinbrickworkorstonework = 452120012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 20)]
		Other = 452120020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Under eaves", 5)]
		Undereaves = 452120005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Under hanging tile / slate", 0)]
		Underhangingtileslate = 452120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Under lead flashing (or equivalent)", 8)]
		Underleadflashing_orequivalent = 452120008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Under peeled paintwork or lifted rendering", 3)]
		Underpeeledpaintworkorliftedrendering = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Under roof tile / slate", 1)]
		Underrooftileslate = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Under weatherboarding", 4)]
		Underweatherboarding = 452120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Within a cave or underground natural structure", 19)]
		Withinacaveorundergroundnaturalstructure = 452120019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Within a cellar", 14)]
		Withinacellar = 452120014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Within a loft void", 10)]
		Withinaloftvoid = 452120010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Within a tree", 18)]
		Withinatree = 452120018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Within a wall", 2)]
		Withinawall = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Within existing bat box", 11)]
		Withinexistingbatbox = 452120011,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Modificationchanges
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Change in Licensee", 0)]
		ChangeinLicensee = 452120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Change in Named Ecologist", 1)]
		ChangeinNamedEcologist = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Changes to compensation", 8)]
		Changestocompensation = 452120008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Changes to figures for EPS licences", 13)]
		ChangestofiguresforEPSlicences = 452120013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Changes to habitat maintenance", 10)]
		Changestohabitatmaintenance = 452120010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Changes to habitat management", 9)]
		Changestohabitatmanagement = 452120009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Changes to post-development monitoring", 11)]
		Changestopostdevelopmentmonitoring = 452120011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Changes to the licensed methods", 7)]
		Changestothelicensedmethods = 452120007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Changes to the Master Plan (phased or multi-plot development licences only)", 12)]
		ChangestotheMasterPlan_phasedormultiplotdevelopmentlicencesonly = 452120012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Changes to the timing of works", 6)]
		Changestothetimingofworks = 452120006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Change to Additional Authorised Persons", 2)]
		ChangetoAdditionalAuthorisedPersons = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Change to impacts", 5)]
		Changetoimpacts = 452120005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Change to planning consent", 3)]
		Changetoplanningconsent = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Increase in licensable number of the species", 4)]
		Increaseinlicensablenumberofthespecies = 452120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 14)]
		Other = 452120014,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_modificationrequest_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_monitoringmethodtechniques
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Acoustic monitoring", 3)]
		Acousticmonitoring = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Aerial inspections (involving trees)", 10)]
		Aerialinspections_involvingtrees = 452120010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ALBST", 4)]
		ALBST = 452120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bat box checks / physical inspections", 1)]
		Batboxchecksphysicalinspections = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Building internals / externals inspections", 7)]
		Buildinginternalsexternalsinspections = 452120007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dawn re-entry", 6)]
		Dawnreentry = 452120006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DNA analysis of droppings", 5)]
		DNAanalysisofdroppings = 452120005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Emergence surveys", 2)]
		Emergencesurveys = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Environmental conditions (e.g. lighting, airflow, humidity and temperature)", 11)]
		Environmentalconditions_eglightingairflowhumidityandtemperature = 452120011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Infra red imaging", 8)]
		Infraredimaging = 452120008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("N/A - None proposed", 0)]
		NANoneproposed = 452120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Thermal imaging", 9)]
		Thermalimaging = 452120009,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Newlshasundertaken
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Completed an HRA LSE Rapid Screening Tool (lower risk cases) or HRA LSE Screening" +
			" using the full template (higher risk cases)", 2)]
		CompletedanHRALSERapidScreeningTool_lowerriskcasesorHRALSEScreeningusingthefulltemplate_higherriskcases = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Drafted additional licence conditions should a licence be granted", 0)]
		Draftedadditionallicenceconditionsshouldalicencebegranted = 452120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Drafted a new HRA Appropriate Assessment", 3)]
		DraftedanewHRAAppropriateAssessment = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Proposed a licence note to confirm consenting/assenting requirements for SSSIs", 1)]
		ProposedalicencenotetoconfirmconsentingassentingrequirementsforSSSIs = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Updated a previous HRA or referenced a shadow HRA Appropriate Assessment", 4)]
		UpdatedapreviousHRAorreferencedashadowHRAAppropriateAssessment = 452120004,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_OnorAdjacentto
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Next to", 1)]
		Nextto = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("On", 0)]
		On = 100000000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Outcome
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Granted", 0)]
		Granted = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not Granted", 1)]
		NotGranted = 100000001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_PermissionType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Demolition consent", 1)]
		Demolitionconsent = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Development Consent Order", 6)]
		DevelopmentConsentOrder = 452120007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Highways Act consent", 3)]
		HighwaysActconsent = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Listed building consent", 2)]
		Listedbuildingconsent = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mineral consent", 4)]
		Mineralconsent = 452120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Planning permission", 0)]
		Planningpermission = 452120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tree preservation order", 5)]
		Treepreservationorder = 452120006,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_planningconsent_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Planningpermissionstype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Full", 0)]
		Full = 452120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hybrid", 2)]
		Hybrid = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 3)]
		Other = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outline", 1)]
		Outline = 452120001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_PostImpactPopulationMonitoring
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("No ", 2)]
		No = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Yes, I monitoring proposed", 0)]
		YesImonitoringproposed = 452120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Yes, monitoring not required", 1)]
		Yesmonitoringnotrequired = 452120001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_PreferredContact
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Applicant", 0)]
		Applicant = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Named Ecologist", 1)]
		NamedEcologist = 100000001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_PreviousApplicationOutcome
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Advice Only", 2)]
		AdviceOnly = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Deferred", 3)]
		Deferred = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Granted", 0)]
		Granted = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not Granted", 1)]
		NotGranted = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not yet known", 4)]
		Notyetknown = 100000004,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_PriorAdviceforthisapplication
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DAS - discretionary advice", 0)]
		DASdiscretionaryadvice = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PSS - pre-submission screening", 1)]
		PSSpresubmissionscreening = 100000001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Priority
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("1", 0, "#D61952")]
		_1 = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("2", 1, "#8C19D6")]
		_2 = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("3", 2, "#194DD6")]
		_3 = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("4", 3, "#19D6CB")]
		_4 = 100000003,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Reasonfornopermission
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Health and safety", 1)]
		Healthandsafety = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 2)]
		Other = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Permitted development", 0)]
		Permitteddevelopment = 452120000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Reasonforpause
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Agreed revised deadline - notify only", 3)]
		Agreedreviseddeadlinenotifyonly = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Awaiting Consultee response - notify only", 2)]
		AwaitingConsulteeresponsenotifyonly = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Awaiting information - notify and action to resubmit/clarify etc.", 1)]
		Awaitinginformationnotifyandactiontoresubmitclarifyetc = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Compliance/Enforcement investigation - notify only", 0)]
		ComplianceEnforcementinvestigationnotifyonly = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 5)]
		Other = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Unable to contact applicant - notify only and action to contact us", 4)]
		Unabletocontactapplicantnotifyonlyandactiontocontactus = 100000004,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_ReasonsNewlsConsultationwithAreaTeam
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Check whether separate SSSI consent is required", 1)]
		CheckwhetherseparateSSSIconsentisrequired = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("HRA due to potential impact on SPA/SAC/Ramsar site(s) – advice on likely signific" +
			"ant effects (‘LSE’)", 2)]
		HRAduetopotentialimpactonSPASACRamsarsite_sadviceonlikelysignificanteffects_LSE = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("HRA: Request informal advice on a draft Appropriate Assessment", 3)]
		HRARequestinformaladviceonadraftAppropriateAssessment = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("HRA: Statutory consultation of Appropriate Assessment conclusions", 4)]
		HRAStatutoryconsultationofAppropriateAssessmentconclusions = 452120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Potential impact on SSSI notified feature(s) identified", 0)]
		PotentialimpactonSSSInotifiedfeature_sidentified = 452120000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_RequestType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Modification", 2)]
		Modification = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("New", 0)]
		New = 452120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Resubmission", 1)]
		Resubmission = 452120001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Roosttypes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Day", 1)]
		Day = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Feeding perch", 3)]
		Feedingperch = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hibernation confirmed", 0)]
		Hibernationconfirmed = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Maternity", 7)]
		Maternity = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Night", 4)]
		Night = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Satellite", 5)]
		Satellite = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Swarming or mating", 6)]
		Swarmingormating = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transitional/Occasional", 2)]
		TransitionalOccasional = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Underground - mines, caves, cellars, tunnels or bridges", 8)]
		Undergroundminescavescellarstunnelsorbridges = 100000008,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Setttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("All sett types", 5)]
		Allsetttypes = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Annexe", 2)]
		Annexe = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Main – alternative sett available", 1)]
		Mainalternativesettavailable = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Main - no alternative sett", 0)]
		Mainnoalternativesett = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not Known", 7)]
		NotKnown = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 6)]
		Other = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outlier", 4)]
		Outlier = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Subsidiary", 3)]
		Subsidiary = 100000006,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_SingleorMultipleyearlicence
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Multiple", 1)]
		Multiple = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Single ", 0)]
		Single = 100000000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_site_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_sitetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Marine Nature Reserve (MNR)", 5)]
		MarineNatureReserve_MNR = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("National Nature Reserve (NNR)", 0)]
		NationalNatureReserve_NNR = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ramsar Site", 4)]
		RamsarSite = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Site of Special Scientific Interest (SSSI)", 1)]
		SiteofSpecialScientificInterest_SSSI = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Special Area of Conservation (SAC)", 3)]
		SpecialAreaofConservation_SAC = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Special Protection Area (SPA)", 2)]
		SpecialProtectionArea_SPA = 100000002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_usedonotuse
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Do not use", 1)]
		Donotuse = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Use", 0)]
		Use = 452120000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_whyisamodificationrequired
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Add or remove Licence Annex(es)", 4)]
		AddorremoveLicenceAnnex_es = 452120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Add or remove roost type or species", 3)]
		Addorremoveroosttypeorspecies = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Change Accreditation Level of the Registered Site", 5)]
		ChangeAccreditationLeveloftheRegisteredSite = 452120005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Change of Joint Licensee", 0)]
		ChangeofJointLicensee = 452120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Change of Licensee", 1)]
		ChangeofLicensee = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Increase in number of bats - that changes roost type impacted and requires additi" +
			"onal mitigation and/or compensation", 2)]
		Increaseinnumberofbatsthatchangesroosttypeimpactedandrequiresadditionalmitigationandorcompensation = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Modify compensation due to unexpected finds", 8)]
		Modifycompensationduetounexpectedfinds = 452120008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Modify compensation that will reduce roosting opportunities for the species", 6)]
		Modifycompensationthatwillreduceroostingopportunitiesforthespecies = 452120006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 9)]
		Other = 452120009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reduce monitoring surveys", 7)]
		Reducemonitoringsurveys = 452120007,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_Whynoreasonedstatement
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("conserve and protect listed buildings, scheduled monuments or places o", 1)]
		conserveandprotectlistedbuildingsscheduledmonumentsorplaceso = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("home improvements and small scale housing developments", 0)]
		homeimprovementsandsmallscalehousingdevelopments = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("maintain, repair, improve public buildings or develop public land", 2)]
		maintainrepairimprovepublicbuildingsordeveloppublicland = 100000002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_WithregardtoSSSI
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("N/A - the licensable activity is not proposed within a SSSI site boundary", 0)]
		NAthelicensableactivityisnotproposedwithinaSSSIsiteboundary = 452120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SSSI - no relevant ORNECs have been identified", 1)]
		SSSInorelevantORNECshavebeenidentified = 452120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SSSI - ORNECS have been identified and the applicant is a third party asacting al" +
			"one", 3)]
		SSSIORNECShavebeenidentifiedandtheapplicantisathirdpartyasactingalone = 452120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SSSI - ORNECS have been identified and the applicant is the owner/occupier(or aut" +
			"horised person) ", 2)]
		SSSIORNECShavebeenidentifiedandtheapplicantistheowneroccupier_orauthorisedperson = 452120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SSSI - the applicant is a Public body or other Section 28G authority", 4)]
		SSSItheapplicantisaPublicbodyorotherSection28Gauthority = 452120004,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_yesno
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("No", 1)]
		No = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Yes", 0)]
		Yes = 100000000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_yesnona
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("No", 1)]
		No = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not Applicable", 2)]
		NotApplicable = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Yes", 0)]
		Yes = 100000000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_yesnonotsure
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("No", 1)]
		No = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not Sure", 2)]
		NotSure = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Yes", 0)]
		Yes = 100000000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Task_PriorityCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("High", 2)]
		High = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Low", 0)]
		Low = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Normal", 1)]
		Normal = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Task_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Canceled", 4)]
		Canceled = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Completed", 3)]
		Completed = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Deferred", 5)]
		Deferred = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("In Progress", 1)]
		InProgress = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not Started", 0)]
		NotStarted = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Waiting on someone else", 2)]
		Waitingonsomeoneelse = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum appaction_ClientType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Browser", 0, "#0000ff")]
		Browser = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mobile", 1, "#0000ff")]
		Mobile = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mail App", 2, "#0000ff")]
		MailApp = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum card_Sizes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Small", 0, "#0000ff")]
		Small = 200000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Medium", 1, "#0000ff")]
		Medium = 200000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Large", 2, "#0000ff")]
		Large = 200000002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum credential_UsageType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Connection", 0, null, "authorize this credential in connection", "connection")]
		Connection = 280920000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DesktopScript", 1, null, "authorize this credential in power automate for desktop script", "DesktopScript")]
		DesktopScript = 280920001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum formmappingallowedoperations
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Create", 0)]
		Create = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Update", 1)]
		Update = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_knowledgemanagementsetting_msdyn_actionlist
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Link / unlink article", 0, "#0000ff")]
		Linkunlinkarticle = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Copy URL", 1, "#0000ff")]
		CopyURL = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Link article and email URL", 2, "#0000ff")]
		LinkarticleandemailURL = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Link article and send article content", 3, "#0000ff")]
		Linkarticleandsendarticlecontent = 3,
	}
}
