//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SDDS.Plugin.EBG
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdds_licensableactionState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("sdds_licensableaction")]
	public partial class sdds_licensableaction : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public sdds_licensableaction() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "sdds_licensableaction";
		
		public const string EntitySchemaName = "sdds_licensableaction";
		
		public const string PrimaryIdAttribute = "sdds_licensableactionid";
		
		public const string PrimaryNameAttribute = "sdds_species";
		
		public const string EntityLogicalCollectionName = "sdds_licensableactions";
		
		public const string EntitySetName = "sdds_licensableactions";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_activebadgersett")]
		public System.Nullable<bool> sdds_activebadgersett
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("sdds_activebadgersett");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_activebadgersett");
				this.SetAttributeValue("sdds_activebadgersett", value);
				this.OnPropertyChanged("sdds_activebadgersett");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_applicationid")]
		public Microsoft.Xrm.Sdk.EntityReference sdds_applicationid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("sdds_applicationid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_applicationid");
				this.SetAttributeValue("sdds_applicationid", value);
				this.OnPropertyChanged("sdds_applicationid");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_applicationsubject")]
		public virtual sdds_ApplicationSubject? sdds_applicationsubject
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sdds_ApplicationSubject?)(EntityOptionSetEnum.GetEnum(this, "sdds_applicationsubject")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_applicationsubject");
				this.SetAttributeValue("sdds_applicationsubject", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("sdds_applicationsubject");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_applicationtypeid")]
		public string sdds_applicationtypeid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdds_applicationtypeid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_applicationtypeid");
				this.SetAttributeValue("sdds_applicationtypeid", value);
				this.OnPropertyChanged("sdds_applicationtypeid");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_applicationtypeid2")]
		public string sdds_applicationtypeid2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdds_applicationtypeid2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_applicationtypeid2");
				this.SetAttributeValue("sdds_applicationtypeid2", value);
				this.OnPropertyChanged("sdds_applicationtypeid2");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_badgersettbereopenedafterdevelopment")]
		public System.Nullable<bool> sdds_badgersettbereopenedafterdevelopment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("sdds_badgersettbereopenedafterdevelopment");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_badgersettbereopenedafterdevelopment");
				this.SetAttributeValue("sdds_badgersettbereopenedafterdevelopment", value);
				this.OnPropertyChanged("sdds_badgersettbereopenedafterdevelopment");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_gridfinderurl")]
		public string sdds_gridfinderurl
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdds_gridfinderurl");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_gridfinderurl");
				this.SetAttributeValue("sdds_gridfinderurl", value);
				this.OnPropertyChanged("sdds_gridfinderurl");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_howmanyentranceholesareactive")]
		public System.Nullable<int> sdds_howmanyentranceholesareactive
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("sdds_howmanyentranceholesareactive");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_howmanyentranceholesareactive");
				this.SetAttributeValue("sdds_howmanyentranceholesareactive", value);
				this.OnPropertyChanged("sdds_howmanyentranceholesareactive");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_impactonroost")]
		public virtual sdds_ImpactforRoost? sdds_impactonroost
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sdds_ImpactforRoost?)(EntityOptionSetEnum.GetEnum(this, "sdds_impactonroost")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_impactonroost");
				this.SetAttributeValue("sdds_impactonroost", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("sdds_impactonroost");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_installationcreationdates")]
		public string sdds_installationcreationdates
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdds_installationcreationdates");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_installationcreationdates");
				this.SetAttributeValue("sdds_installationcreationdates", value);
				this.OnPropertyChanged("sdds_installationcreationdates");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_licensableactionid")]
		public System.Nullable<System.Guid> sdds_licensableactionId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("sdds_licensableactionid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_licensableactionId");
				this.SetAttributeValue("sdds_licensableactionid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("sdds_licensableactionId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_licensableactionid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.sdds_licensableactionId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_license")]
		public Microsoft.Xrm.Sdk.EntityReference sdds_license
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("sdds_license");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_license");
				this.SetAttributeValue("sdds_license", value);
				this.OnPropertyChanged("sdds_license");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_licenseactivityid")]
		public Microsoft.Xrm.Sdk.EntityReference sdds_licenseactivityid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("sdds_licenseactivityid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_licenseactivityid");
				this.SetAttributeValue("sdds_licenseactivityid", value);
				this.OnPropertyChanged("sdds_licenseactivityid");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_locationofcompensationmeasures")]
		public virtual sdds_Compensationmeasureslocation? sdds_locationofcompensationmeasures
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sdds_Compensationmeasureslocation?)(EntityOptionSetEnum.GetEnum(this, "sdds_locationofcompensationmeasures")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_locationofcompensationmeasures");
				this.SetAttributeValue("sdds_locationofcompensationmeasures", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("sdds_locationofcompensationmeasures");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_locationofroost")]
		public virtual sdds_Locationofroost? sdds_locationofroost
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sdds_Locationofroost?)(EntityOptionSetEnum.GetEnum(this, "sdds_locationofroost")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_locationofroost");
				this.SetAttributeValue("sdds_locationofroost", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("sdds_locationofroost");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_maximumnoofsubject")]
		public System.Nullable<int> sdds_maximumnoofsubject
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("sdds_maximumnoofsubject");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_maximumnoofsubject");
				this.SetAttributeValue("sdds_maximumnoofsubject", value);
				this.OnPropertyChanged("sdds_maximumnoofsubject");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_method")]
		public virtual System.Collections.Generic.IEnumerable<sdds_LicenseMethod1> sdds_method
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return EntityOptionSetEnum.GetMultiEnum<sdds_LicenseMethod1>(this, "sdds_method");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_method");
				this.SetAttributeValue("sdds_method", EntityOptionSetEnum.GetMultiEnum(this, "sdds_method", value));
				this.OnPropertyChanged("sdds_method");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_newroostdimensiondetailsandfeatures")]
		public string sdds_newroostdimensiondetailsandfeatures
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdds_newroostdimensiondetailsandfeatures");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_newroostdimensiondetailsandfeatures");
				this.SetAttributeValue("sdds_newroostdimensiondetailsandfeatures", value);
				this.OnPropertyChanged("sdds_newroostdimensiondetailsandfeatures");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_noentranceholeofbadgersett")]
		public System.Nullable<int> sdds_noentranceholeofbadgersett
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("sdds_noentranceholeofbadgersett");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_noentranceholeofbadgersett");
				this.SetAttributeValue("sdds_noentranceholeofbadgersett", value);
				this.OnPropertyChanged("sdds_noentranceholeofbadgersett");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_noofbreedingsitesimpacted")]
		public System.Nullable<int> sdds_noofbreedingsitesimpacted
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("sdds_noofbreedingsitesimpacted");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_noofbreedingsitesimpacted");
				this.SetAttributeValue("sdds_noofbreedingsitesimpacted", value);
				this.OnPropertyChanged("sdds_noofbreedingsitesimpacted");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_noofrestingplacesimpacted")]
		public System.Nullable<int> sdds_noofrestingplacesimpacted
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("sdds_noofrestingplacesimpacted");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_noofrestingplacesimpacted");
				this.SetAttributeValue("sdds_noofrestingplacesimpacted", value);
				this.OnPropertyChanged("sdds_noofrestingplacesimpacted");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_numberofaccesspoints")]
		public System.Nullable<int> sdds_numberofaccesspoints
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("sdds_numberofaccesspoints");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_numberofaccesspoints");
				this.SetAttributeValue("sdds_numberofaccesspoints", value);
				this.OnPropertyChanged("sdds_numberofaccesspoints");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_osgridref")]
		public string sdds_osgridref
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdds_osgridref");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_osgridref");
				this.SetAttributeValue("sdds_osgridref", value);
				this.OnPropertyChanged("sdds_osgridref");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_peakcount")]
		public string sdds_peakcount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdds_peakcount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_peakcount");
				this.SetAttributeValue("sdds_peakcount", value);
				this.OnPropertyChanged("sdds_peakcount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_proposedenddate")]
		public System.Nullable<System.DateTime> sdds_proposedenddate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("sdds_proposedenddate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_proposedenddate");
				this.SetAttributeValue("sdds_proposedenddate", value);
				this.OnPropertyChanged("sdds_proposedenddate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_proposedstartdate")]
		public System.Nullable<System.DateTime> sdds_proposedstartdate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("sdds_proposedstartdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_proposedstartdate");
				this.SetAttributeValue("sdds_proposedstartdate", value);
				this.OnPropertyChanged("sdds_proposedstartdate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_roosttypeaffected")]
		public virtual System.Collections.Generic.IEnumerable<sdds_Roosttypes> sdds_roosttypeaffected
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return EntityOptionSetEnum.GetMultiEnum<sdds_Roosttypes>(this, "sdds_roosttypeaffected");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_roosttypeaffected");
				this.SetAttributeValue("sdds_roosttypeaffected", EntityOptionSetEnum.GetMultiEnum(this, "sdds_roosttypeaffected", value));
				this.OnPropertyChanged("sdds_roosttypeaffected");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_setttype")]
		public virtual sdds_Setttype? sdds_setttype
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sdds_Setttype?)(EntityOptionSetEnum.GetEnum(this, "sdds_setttype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_setttype");
				this.SetAttributeValue("sdds_setttype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("sdds_setttype");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_specieid")]
		public Microsoft.Xrm.Sdk.EntityReference sdds_specieid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("sdds_specieid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_specieid");
				this.SetAttributeValue("sdds_specieid", value);
				this.OnPropertyChanged("sdds_specieid");
			}
		}
		
		/// <summary>
		/// Required name field
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_species")]
		public string sdds_species
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdds_species");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_species");
				this.SetAttributeValue("sdds_species", value);
				this.OnPropertyChanged("sdds_species");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_speciesubjectid")]
		public Microsoft.Xrm.Sdk.EntityReference sdds_speciesubjectid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("sdds_speciesubjectid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_speciesubjectid");
				this.SetAttributeValue("sdds_speciesubjectid", value);
				this.OnPropertyChanged("sdds_speciesubjectid");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_typeofcompensationmesaures")]
		public virtual sdds_compensationmesaurestypes? sdds_typeofcompensationmesaures
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sdds_compensationmesaurestypes?)(EntityOptionSetEnum.GetEnum(this, "sdds_typeofcompensationmesaures")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_typeofcompensationmesaures");
				this.SetAttributeValue("sdds_typeofcompensationmesaures", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("sdds_typeofcompensationmesaures");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_usedonotuse")]
		public System.Nullable<bool> sdds_usedonotuse
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("sdds_usedonotuse");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_usedonotuse");
				this.SetAttributeValue("sdds_usedonotuse", value);
				this.OnPropertyChanged("sdds_usedonotuse");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_useinlicence")]
		public virtual sdds_usedonotuse? sdds_useinlicence
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sdds_usedonotuse?)(EntityOptionSetEnum.GetEnum(this, "sdds_useinlicence")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_useinlicence");
				this.SetAttributeValue("sdds_useinlicence", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("sdds_useinlicence");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_willtheroostbemodified")]
		public virtual sdds_yesno? sdds_willtheroostbemodified
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sdds_yesno?)(EntityOptionSetEnum.GetEnum(this, "sdds_willtheroostbemodified")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_willtheroostbemodified");
				this.SetAttributeValue("sdds_willtheroostbemodified", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("sdds_willtheroostbemodified");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_willtheroostberetained")]
		public virtual sdds_yesno? sdds_willtheroostberetained
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sdds_yesno?)(EntityOptionSetEnum.GetEnum(this, "sdds_willtheroostberetained")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_willtheroostberetained");
				this.SetAttributeValue("sdds_willtheroostberetained", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("sdds_willtheroostberetained");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_yesroostwillbemodified")]
		public string sdds_yesroostwillbemodified
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdds_yesroostwillbemodified");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_yesroostwillbemodified");
				this.SetAttributeValue("sdds_yesroostwillbemodified", value);
				this.OnPropertyChanged("sdds_yesroostwillbemodified");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_yesroostwillberetained")]
		public string sdds_yesroostwillberetained
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdds_yesroostwillberetained");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_yesroostwillberetained");
				this.SetAttributeValue("sdds_yesroostwillberetained", value);
				this.OnPropertyChanged("sdds_yesroostwillberetained");
			}
		}
		
		/// <summary>
		/// Status of the Licensable Action
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<SDDS.Plugin.EBG.sdds_licensableactionState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((SDDS.Plugin.EBG.sdds_licensableactionState)(System.Enum.ToObject(typeof(SDDS.Plugin.EBG.sdds_licensableactionState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Licensable Action
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual sdds_licensableaction_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sdds_licensableaction_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:N sdds_licensableaction_sdds_licensemethod_
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sdds_licensableaction_sdds_licensemethod_")]
		public System.Collections.Generic.IEnumerable<SDDS.Plugin.EBG.sdds_licensemethod> sdds_licensableaction_sdds_licensemethod_
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<SDDS.Plugin.EBG.sdds_licensemethod>("sdds_licensableaction_sdds_licensemethod_", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_licensableaction_sdds_licensemethod_");
				this.SetRelatedEntities<SDDS.Plugin.EBG.sdds_licensemethod>("sdds_licensableaction_sdds_licensemethod_", null, value);
				this.OnPropertyChanged("sdds_licensableaction_sdds_licensemethod_");
			}
		}
		
		/// <summary>
		/// N:1 sdds_licensableaction_applicationid_sdds_
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_applicationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sdds_licensableaction_applicationid_sdds_")]
		public SDDS.Plugin.EBG.sdds_application sdds_licensableaction_applicationid_sdds_
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SDDS.Plugin.EBG.sdds_application>("sdds_licensableaction_applicationid_sdds_", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_licensableaction_applicationid_sdds_");
				this.SetRelatedEntity<SDDS.Plugin.EBG.sdds_application>("sdds_licensableaction_applicationid_sdds_", null, value);
				this.OnPropertyChanged("sdds_licensableaction_applicationid_sdds_");
			}
		}
		
		/// <summary>
		/// N:1 sdds_licensableaction_sdds_license_sdds_l
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_license")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sdds_licensableaction_sdds_license_sdds_l")]
		public SDDS.Plugin.EBG.sdds_license sdds_licensableaction_sdds_license_sdds_l
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SDDS.Plugin.EBG.sdds_license>("sdds_licensableaction_sdds_license_sdds_l", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_licensableaction_sdds_license_sdds_l");
				this.SetRelatedEntity<SDDS.Plugin.EBG.sdds_license>("sdds_licensableaction_sdds_license_sdds_l", null, value);
				this.OnPropertyChanged("sdds_licensableaction_sdds_license_sdds_l");
			}
		}
		
		/// <summary>
		/// N:1 sdds_licenseActivity_sdds_licenseactivity
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdds_licenseactivityid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sdds_licenseActivity_sdds_licenseactivity")]
		public SDDS.Plugin.EBG.sdds_licenseActivity sdds_licenseActivity_sdds_licenseactivity
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<SDDS.Plugin.EBG.sdds_licenseActivity>("sdds_licenseActivity_sdds_licenseactivity", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdds_licenseActivity_sdds_licenseactivity");
				this.SetRelatedEntity<SDDS.Plugin.EBG.sdds_licenseActivity>("sdds_licenseActivity_sdds_licenseactivity", null, value);
				this.OnPropertyChanged("sdds_licenseActivity_sdds_licenseactivity");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public sdds_licensableaction(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["sdds_licensableactionid"] = base.Id;
                        break;
                    case "sdds_licensableactionid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}